spring.application.name=rivarly

#DATABASE CONNECTION SETTINGS

spring.datasource.url=jdbc:postrgesql://localhost:5432/rivarly

spring.datasource.username=postgres
spring.datasource.password=postgres0999

spring.datasource.driver-class-name=org.postgresql.Driver

#HIBERNATE SETTING

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQlDialect

#show sqlmessage in LOG
spring.jpa.show-sql=true

#update for save data, create for clean data
spring.jpa.hibernate.ddl-auto=update

#SPRING SECURITY SETTINGS

spring.security.user.name=admin
spring.security.user.password=admin0999
spring.security.user.roles=admin

#ALLOWED ORIGINGS
cors.allowedOrigin=http://localhost:5173

#SECRET KEY
jwt.secretKey=rpf3ssdt4t6ujj653c332c335v567]43[23p64p2pl43l2c3rh6ytrsse42673rdec
jwt.expiration=86400000