spring.application.name=rivarly

#SECURITY DATA IMPORT
spring.config.import=optional:file:./src/main/resources/secrets.properties

#DATABASE CONNECTION SETTINGS

spring.datasource.url=jdbc:postgresql://localhost:5432/rivarly_db

spring.datasource.driver-class-name=org.postgresql.Driver

#HIBERNATE SETTING

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#show sqlmessage in LOG
spring.jpa.show-sql=true

#update for save data, create for clean data
spring.jpa.hibernate.ddl-auto=create

#MinIO
minio.url=http://localhost:9000
minio.bucket-name=rivarly-images

#ALLOWED ORIGINGS
cors.allowedOrigin=http://localhost:5173

#JWT
jwt.expirationMs=1800000
jwt.refreshExpirationMs=86400000

#DOCKER COMPOSE
spring.docker.compose.lifecycle-management=start-only

#DATABASE INITIALIZATION
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#SWAGER
springdoc.swagger-ui.path=/swagger-dock.html
springdoc.swagger-ui.operationsSorter=method